### ISSUE TITLE
Allow users to see more past transactions

### ISSUE THREAD

**Issue by thalvors** [chezbob/chezbob-legacy#12]
Right now users can look at past transactions, but only 10 of them.  Since some users buy 3 or so items a day, this isn't very much history.  We should let this option go back further.  This probably requires some UI changes, since I think you have to scroll to the end to go back (or use the mouse).  I'm not positive on that, but whoever is making this change should investigate.

**Comment by no2chem** [comment]
This is fixed, now you can look back at the entire history.
