### ISSUE TITLE
Firewall Rules on Chezbob and Soda

### ISSUE THREAD

**Issue by jdeblasio** [chezbob/chezbob-legacy#14]
Both of these machines have no firewall setup whatsoever, and soda's RPC, at least, will happily accept connections from anywhere.

We should setup rules for each of these machines to only accept connections from the appropriate sources (chezbob/soda/the tablet).

I recommend ufw. It's just a friendly wrapper around iptables, and is already installed on soda at least.

**Comment by d1m0** [comment]
We did it using iptables. Both machines are accessible from the UCSD network only.
