### ISSUE TITLE
Create Script for Adding New Items

### ISSUE THREAD

**Issue by d1m0** [chezbob/chezbob-legacy#19]
Adding an item involves updating multiple tables. Specifically the per-item prices needs to be updated based on the bulk price and the overhead. This is currently done by admin/update_prices once a day (ran by cron). While this still needs to be ran (prices change for existing items), it would be nice to automate adding new items.

**Comment by jdeblasio** [comment]
Adding new items is a rare and manual process, so the admin interface is the right place for this.

Prices are now auto-updated every time there's an order.
