### ISSUE TITLE
Make soda machine vend properly

### ISSUE THREAD

**Issue by thalvors** [chezbob/chezbob-legacy#2]
The soda machine currently does not vend sodas.  We previously believed this was due to faulty hardware, but now no2chem believes it is because of the way python interacts with the hardware.  Last I heard, no2chem intended to write some C++ code to interface properly and have python call that.  no2chem, please keep this up to date as you make progress / find problems.

**Comment by no2chem** [comment]
I got the controller working today. It turns out that I wasn't sending the
acknowledgement (wasn't well documented in the code). Also I fixed the
broken hopper and I think it is dispensing soda properly.

Currently the soda machine is in freevend mode but that will get fixed soon.
