### ISSUE TITLE
Look at soda status from the web

### ISSUE THREAD

**Issue by thalvors** [chezbob/chezbob-legacy#29]
We should make a web page that shows the current status of soda in the machine.  We can't get soda counts without requiring restockers to say how many they put in, but we can use vend status as a "has soda" vs "does not have soda".  This is made more complicated because we just get "VEND OK" vs "VEND FAIL" from the soda machine, so we'll have to guess what "VEND FAIL" means (if it's temporary or if the soda machine is empty) based on just these two values.  i.e. if nothing else happens and we see a VEND FAIL we can mark it as empty, but if we see a bunch of signals in a small time span, one of which is VEND OK and the rest of which are VEND FAIL, maybe someone was just spamming the button.  This might take some tuning and might not work at all, but it's a much requested feature so we should try.

**Comment by d1m0** [comment]
Now available at:
http://soda.ucsd.edu:8080/static/soda_status.html
