### ISSUE TITLE
Make deposits work

### ISSUE THREAD

**Issue by thalvors** [chezbob/chezbob-legacy#3]
Deposits currently work sometimes, but the fail case is that the soda machine just eats the money.  Deposits have been disabled for now to prevent this from happening.

The bill acceptor has an escrow mode, where it holds the bill until the software tells it what to do, and then accepts/rejects from there.  no2chem previously had problems with escrow mode but I forget what they were.  Talk to him to figure out what's going on and what is required to fix it.

**Comment by jdeblasio** [comment]
Karl solved this, like a boss, some time ago.
