### ISSUE TITLE
Cleaner ansible setup

### ISSUE THREAD

**Issue by thalvors** [chezbob/chezbob-legacy#4]
Right now, ansible installs only the packages needed to make the new code run, but there are a lot of other setup tasks needed to get chez bob itself to run.  It'd be great if this stuff was all included in the ansible scripts.  There are also some half-implemented features, like installing and running the upstart scripts.

This involves the following steps at a minimum, and maybe some others I'm forgetting:
1.  Look at the chez bob wiki to see our notes on machine reinstalls.  Convert those tasks to an ansible playbook.
2.  Make sure the current scripts work properly.  Unfortunately this is hard to test since we don't have spare hardware or anything lying around.
3.  In the chezbob/admin directory, there is a crontab.  It is split into two halves via comments, describing which pieces should run on which machine.  Installing this cron job should be included as well.  You are welcome to rewrite/refactor any of the cron tasks if it makes this easier.  The dependencies of these cron jobs are not well documented, but include things like installing ghostscript (to create the finance pdf).

**Comment by jdeblasio** [comment]
Ansible is comically out of date at this point. Closing for now :-(
