### ISSUE TITLE
Price check for soda machine

### ISSUE THREAD

**Issue by scauligi** [chezbob/chezbob-legacy#45]
When pressing a button but not having logged in / inserted money, soda machine should display the price of the associated beverage (just as scanning an item displays its price).

**Comment by drichmond** [comment]
And maybe the quantity left?

**Comment by jdeblasio** [comment]
This could actually be as many as four issues:
1. Quickly fix the current UI to enable this. Wouldn't be hard.
2. An issue for a future UI to have it there.
3/4. Track and support current stock levels. We don't really do this anymore.

**Comment by drichmond** [comment]
My bad, I thought we still did 3/4.

**Comment by jdeblasio** [comment]
It's still in the UI, but the current restockers aren't necessarily keeping up with it. Plus, because of the crappy kiosk software we're using, it gets pushed off the screen. There's no inherent limitation to keep us from doing 3/4.
