### ISSUE TITLE
Reterminate ethernet cables

### ISSUE THREAD

**Issue by jdeblasio** [chezbob/chezbob-legacy#56]
The ethernet run that we ran to let the soda machine talk to the large tablet is buggy.

Karl downgraded the connection to 10M, but it's capable of 1G in theory.

We think the problem is at the jacks. The first thing to try is to reterminate the connections.

Joe has the proper tools for this in his office.

This is a bounty-eligible bug.

**Comment by drichmond** [comment]
We also need a longer ethernet cable to the RasPi

(Replacing the ethernet cable is not a bounty-eligible issue)

**Comment by jdeblasio** [comment]
Bam. Done by supersat + dimo.
