### ISSUE TITLE
Soda Tablet Auto-capitalization / Username Case

### ISSUE THREAD

**Issue by scauligi** [chezbob/chezbob-legacy#59]
When logging in "manually" from the soda tablet, the keyboard automatically capitalizes the first letter. This is a problem since usernames are case sensitive.

(via Stefan)

**Comment by jdeblasio** [comment]
I'll leave this open, since it'd be nice to have it not auto-capitalize.

HOWEVER, usernames are no longer case sensitive. So you can tell him to not worry about it.

Useful: https://developers.google.com/web/updates/2015/04/autocapitalize?hl=en

**Comment by jdeblasio** [comment]
Thanks, Sunjay!
