### ISSUE TITLE
Lock down interfaces

### ISSUE THREAD

**Issue by thalvors** [chezbob/chezbob-legacy#6]
The interfaces are just browsers pointing at the right web pages.  They work mostly well, until people start messing with them.  The terminal is Chromium and at some point someone installed an extension to re-write parts of the interface, and it's possible to get to the home screen of the Nexus tablet.  These sorts of issues should be fixed.

**Comment by jdeblasio** [comment]
I've made it slightly more difficult to get to a command prompt on the non-soda machine. No promises it'll be worth much.

**Comment by jdeblasio** [comment]
We have mostly solved this. (It's still possible to get a terminal login prompt on the primary interface, but I don't think that's a problem).
