### ISSUE TITLE
Prevent transfers between users from decrementing sender's balance before validating recipient

### ISSUE THREAD

**Issue by drichmond** [chezbob/chezbob-legacy#61]
If you try to transfer money with an incorrect UID, it decrements your balance. 

Also, add a message in the log if a transfer fails (invalid UID, and insufficient balance)

**Comment by drichmond** [comment]
I offer a $1-$5 sliding bounty depending on how much effort it takes, and as testing for whether your change fixes the issue.

**Comment by jdeblasio** [comment]
This is confirmed, and happened to another user yesterday.

Chez Bob is offering an additional bounty of at least $5. I consider this a critical bug.

By UID, Dustin means username.

In particular, the system decrements your balance in the users table for the full amount, and then inserts transactions into the transactions table with a $0 value.

This whole thing should be happening in a transaction, and I'm surprised that it's not.

**Comment by scauligi** [comment]
I've got a possible fix incoming. Needs testing first though.

**Comment by drichmond** [comment]
That's the purpose of my bounty -- you only get it if you can successfully
transfer it to yourself.

**Comment by scauligi** [comment]
fixed by commit 707f42796430490c1f65f17faa38488a292fdd82
