### ISSUE TITLE
Rejecting bills but still adding cash to account

### ISSUE THREAD

**Issue by jdeblasio** [chezbob/chezbob-legacy#66]
We've had a few reports of the soda machine rejecting bills, but still crediting accounts. That seems bad.

Nishant (username nibhaska) had this happen twice in a row at/around 7/5/16 15:44:40.

We need someone to figure out why this is happening, and bug-fix accordingly.

**Comment by drichmond** [comment]
Karl went in to check whether the bill collector was full yesterday, but had issues getting into the closet…

**Comment by jdeblasio** [comment]
Key will be back tomorrow, but the bill collector isn't full. It only has ~30 bills in it.

**Comment by scauligi** [comment]
@jdeblasio can you post or otherwise send me the MDB command logs for nibhaska's session?
and/or the one that just happened as well.

**Comment by jdeblasio** [comment]
Fixed, I think, by 7e21f81.
