### ISSUE TITLE
Investigate rollbacks in SQLAlchemy

### ISSUE THREAD

**Issue by thalvors** [chezbob/chezbob-legacy#8]
I've noticed SQLAlchemy does rollbacks when making purchases or logging in, although all database tables are updated successfully.  Someone should figure out if this is a problem and/or how to avoid it.

**Comment by no2chem** [comment]
http://docs.sqlalchemy.org/en/rel_0_8/faq.html#why-does-sqlalchemy-issue-so-many-rollbacks

**Comment by thalvors** [comment]
Awesome, thanks for the info, sounds like we can just close this.
