### ISSUE TITLE
Do better logging

### ISSUE THREAD

**Issue by thalvors** [chezbob/chezbob-legacy#9]
Right now, our logging is mostly the SQLAlchemy debugging, which is a lot of verbose dumps of SQL queries, most of which work.  We should disable this or lower the logging to error states and add some of our own.  This would make it much easier to debug broken or in development code.

At some point someone along the line is also catching and ignoring exceptions in the JSON server, that's fine but we should make them print somewhere so we can look at them later.  This caused me some headaches when implementing aggregate_purchases.

**Comment by thalvors** [comment]
I made some progress on this today.  I'm using python's logging module, which lets you specify the format and level of log messages and is super easy to use.  Flask lets you create a logging module and pass it into the constructor, which is what we're doing now.

There are two to-dos and reasons this task isn't closed yet.  First, I've only put some pretty basic debugging into the soda_serve.py module, and even then only on the functions I understand.  Second, I haven't figured out how to suppress SQLAlchemy's giant debug messages.  I just need to look through their API a bit and find the right way to do this, we shouldn't be setting the SQLALCHEMY_ECHO variable anymore but that didn't do it.

**Comment by no2chem** [comment]
This is closed now that we are using the node version. It also logs everything on the client side now and has log levels.
